{"name": "test_unauthorized_access", "status": "passed", "description": "Проверка отказа в доступе при использовании недействительного API ключа.", "steps": [{"name": "Получение задачи по ID: 'nonexistent_id'", "status": "passed", "parameters": [{"name": "task_id", "value": "'nonexistent_id'"}], "start": 1745262404222, "stop": 1745262404475}], "start": 1745262404222, "stop": 1745262404475, "uuid": "b8414fbc-b829-4a61-8f6a-6524ae842453", "historyId": "9cba1e9a7f27cb6079dcba3f607f479d", "testCaseId": "9cba1e9a7f27cb6079dcba3f607f479d", "fullName": "tests.api.test_tasks#test_unauthorized_access", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "2272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}