{"name": "test_create_task_negative[task_data5-404-list_id]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 404, got 400\nassert 400 == 404\n +  where 400 = <Response [400]>.status_code", "trace": "tests\\api\\test_tasks.py:120: in test_create_task_negative\n    assert response.status_code == expected_status, (\nE   AssertionError: Expected 404, got 400\nE   assert 400 == 404\nE    +  where 400 = <Response [400]>.status_code"}, "description": "Негативные тесты создания задач с некорректными данными.", "steps": [{"name": "Создание задачи в списке с ID: 'invalid_list_123'", "status": "passed", "steps": [{"name": "POST /list/invalid_list_123/task", "status": "passed", "start": 1745075072096, "stop": 1745075072189}], "parameters": [{"name": "list_id", "value": "'invalid_list_123'"}, {"name": "task_data", "value": "{}"}], "start": 1745075072096, "stop": 1745075072189}], "parameters": [{"name": "task_data", "value": "{'list_id': 'invalid_list_123'}"}, {"name": "expected_status", "value": "404"}, {"name": "error_keyword", "value": "'list_id'"}], "start": 1745075072096, "stop": 1745075072189, "uuid": "a6be1299-2d90-4564-bee8-8f1ef27ef0b7", "historyId": "9d373edec0e7cfbe3251a14370cce598", "testCaseId": "e68a266bd94a31c77d043e15942220bb", "fullName": "tests.api.test_tasks#test_create_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "17384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}