{"name": "test_update_task_negative", "status": "passed", "description": "Негативный тест: передача некорректных данных при обновлении задачи.", "steps": [{"name": "Обновление задачи по ID: '86a82gcj7'", "status": "passed", "steps": [{"name": "PUT /task/86a82gcj7", "status": "passed", "start": 1745078828549, "stop": 1745078828631}], "parameters": [{"name": "task_id", "value": "'86a82gcj7'"}, {"name": "task_update", "value": "'invalid_payload'"}], "start": 1745078828549, "stop": 1745078828631}], "start": 1745078828549, "stop": 1745078828632, "uuid": "63a98131-8caa-46da-b1b3-1e6f4d5f66e2", "historyId": "fe5e41104959de7eee0a8bdfa066bd06", "testCaseId": "fe5e41104959de7eee0a8bdfa066bd06", "fullName": "tests.api.test_tasks#test_update_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "12420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}