{"name": "test_update_task_negative", "status": "passed", "description": "Негативный тест: передача некорректных данных при обновлении задачи.", "steps": [{"name": "Обновление задачи по ID: '86a83a7c0'", "status": "passed", "parameters": [{"name": "task_id", "value": "'86a83a7c0'"}, {"name": "task_update", "value": "'invalid_payload'"}], "start": 1745262406465, "stop": 1745262406544}], "start": 1745262406465, "stop": 1745262406545, "uuid": "b267ed9a-1dec-4659-968e-f260717f023b", "historyId": "fe5e41104959de7eee0a8bdfa066bd06", "testCaseId": "fe5e41104959de7eee0a8bdfa066bd06", "fullName": "tests.api.test_tasks#test_update_task_negative", "labels": [{"name": "feature", "value": "Задачи"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "host", "value": "DESKTOP-77BDOFA"}, {"name": "thread", "value": "2272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}